using UnityEngine;

public class PlayerMovement : MonoBehaviour
{


    public float moveSpeed;
    Rigidbody2D rb;


    [HideInInspector]
    public Vector2 moveDir;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
    }

    // Update is called once per frame
    void Update()
    {
        InputManagement();
    }

    void FixedUpdate()
    {
        Move();
    }
    
    void InputManagement()
    {
        //Variables movimiento jugador (dentro de unity)
        float moveX = Input.GetAxisRaw("Horizontal");
        float moveY = Input.GetAxisRaw("Vertical");
     
        moveDir = new Vector2(moveX, moveY).normalized;
    }
    void Move()//Movimiento jugador 
    {
        rb.linearVelocity = new Vector2(moveDir.x * moveSpeed, moveDir.y * moveSpeed);
    }
}
